Repository grafana/k6-operator, pull requests merged in 2025-08, with the labels that each got.

#621 Improve `make help` command
  CONTRIBUTING.md
  Makefile
Labels: maintenance

#622 Small fixes for e2e test suite
  e2e/README.md
  e2e/run-tests.sh
Labels: maintenance, e2e

#633 Add `portName` option to Helm chart
  charts/k6-operator/README.md
  charts/k6-operator/templates/deployment.yaml
  charts/k6-operator/templates/service.yaml
  charts/k6-operator/values.schema.json
  charts/k6-operator/values.yaml
Labels: enhancement, helm
